compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
  deepspeed_multinode_launcher: standard
  deepspeed_config_file: config/ds_stage3_config.json
  zero3_init_flag: false
distributed_type: DEEPSPEED
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
use_cpu: false
downcast_bf16: 'no'
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
